#!/bin/bash

#remote=https
#branch=gh-pages

mv README.md README.md.back
cat README.md.back | sed "s/\(\w*\)\.md/md_\1.html/g" > README.md
doxygen mpi.dox
rm README.md
mv README.md.back README.md

cd gh-pages
git add .
if [[ "$1" -ne "" ]]; then
  git commit -a -m $1; 
else git commit -a -m "Generic Dox Update"; fi
echo -e "OscardR\n" | git push $remote $branch
cd ..